apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: clientID
      value: rs-service-dapr-consumer
    - name: brokers
      value: localhost:9092
    - name: consumerGroup
      value: rs-service-dapr-consumer-group
    - name: authRequired
      value: "false"
