name: Promote rs-metrics-service to Staging/Production

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Target environment to deploy to"
        required: true
        type: choice
        options:
          - stg
          - prod
        default: stg
      image_tag:
        description: "Git tag or image tag to deploy"
        required: true
        type: string

# Prevent concurrent builds of the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  call-remote-image-deploy:
    uses: riversidefm/github-actions/.github/workflows/deploy_image_generic.yml@main
    with:
      image_tag: ${{ github.event.inputs.image_tag }}
      ecr_repository: rs-metrics-service  # ECR repo name
      env_name: ${{ github.event.inputs.target_env }}
      values_file: rs-metrics-service
    secrets:
      AUTOMATION_GITHUB_TOKEN: ${{ secrets.AUTOMATION_GITHUB_TOKEN }}